name: "index-digest Action"
author: "@macbre"
description: "An action to run https://github.com/macbre/index-digest"
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#branding
branding:
  icon: "database"
  color: "green"
inputs:
  index-digest-version:
    description: "The version of index-digest to install"
    required: true
    default: "1.4.0"
runs:
  using: "composite"
  steps:
    # https://hub.docker.com/r/macbre/index-digest
    - shell: bash 
      run: |
        echo "Using index-version v${{ inputs.index-digest-version }} ..."
        docker pull macbre/index-digest:${{ inputs.index-digest-version }}

    - shell: bash
      # run: docker run --network=host -t macbre/index-digest:latest mysql://index_digest:qwerty@debian/index_digest  | head -n 20
      run: docker run --network=host -t macbre/index-digest --version
