name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: "ubuntu-20.04"  # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    strategy:
      fail-fast: false
      matrix:
        index-digest-version:
        - "1.4.0"
        - "latest"

    services:
      # https://hub.docker.com/_/mysql
      database:
        image: "mysql:8.0.22"
        env:
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
            MYSQL_DATABASE: index_digest
        ports:
            - "3310:3306"  # will be listening on 3310 host port
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
      
      - name: Import test schema into the database
        run: |
          mysql --host=127.0.0.1 --port=3310 --user=root --database=index_digest < ./sql/0000_setup.sql

          echo -e "[client]\nuser=digest\npassword=s3cr3t\n" > ~/.my.cnf
          mysql --host=127.0.0.1 --port=3310 --user=digest --database=index_digest < ./sql/0001_redundant_indices.sql
          mysql --host=127.0.0.1 --port=3310 --user=digest --database=index_digest  --execute="SHOW TABLES"

      # docker run --network=host -t macbre/index-digest:latest mysql://index_digest:qwerty@debian/index_digest  | head -n 20
      - name: Run an action
        uses: ./
        with:
          index-digest-version: ${{ matrix.index-digest-version }}
          index-digest-dsn: "mysql://digest:s3cr3t@127.0.0.1:3310/index_digest"
          index-digest-report-file: "./report.yml"

      - name: Check the version and the output file
        run: |
          docker run -t macbre/index-digest:${{ matrix.index-digest-version }} --version
          cat ./report.yml

