name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: "ubuntu-20.04"  # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    strategy:
      fail-fast: false
      matrix:
        index-digest-version: [1.4.0]

    steps:
      - uses: actions/checkout@v2

      - name: Run an action
        uses: ./
        with:
          index-digest-version: ${{ matrix.index-digest-version }}

      - name: Check the version
        run: docker run -t macbre/index-digest:${{ matrix.index-digest-version }} --version
